-- MySQL Script generated by MySQL Workbench
-- Wed Jun  4 01:49:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema demo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `demo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `demo` ;

-- -----------------------------------------------------
-- Table `demo`.`school`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`school` (
                                               `id` INT NOT NULL AUTO_INCREMENT,
                                               `title` VARCHAR(100) NOT NULL,
    `address` VARCHAR(255) NOT NULL,
    `phone` VARCHAR(45) NOT NULL,
    `email` VARCHAR(45) NOT NULL,
    `director_name` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 6
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`schoolclass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`schoolclass` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `grade_level` INT NOT NULL,
                                                    `letter` VARCHAR(1) NOT NULL,
    `school_id` INT NULL DEFAULT NULL,
    `enabled` TINYINT(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (`id`),
    INDEX `school_id` (`school_id` ASC) VISIBLE,
    CONSTRAINT `schoolclass_ibfk_1`
    FOREIGN KEY (`school_id`)
    REFERENCES `demo`.`school` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 11
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`subject` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `subject_name` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 12
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`user` (
                                             `id` INT NOT NULL AUTO_INCREMENT,
                                             `username` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `school_id` INT NULL DEFAULT NULL,
    `enabled` TINYINT(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `login` (`username` ASC) VISIBLE,
    INDEX `school_id_idx` (`school_id` ASC) VISIBLE,
    CONSTRAINT `school_id`
    FOREIGN KEY (`school_id`)
    REFERENCES `demo`.`school` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 15
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`teacher` (
                                                `id` INT NOT NULL AUTO_INCREMENT,
                                                `name` VARCHAR(100) NOT NULL,
    `user_id` INT NULL DEFAULT NULL,
    `enabled` TINYINT(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `user_id` (`user_id` ASC) VISIBLE,
    CONSTRAINT `teacher_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `demo`.`user` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 4
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`schedule`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`schedule` (
                                                 `id` INT NOT NULL AUTO_INCREMENT,
                                                 `day_of_week` VARCHAR(45) NOT NULL,
    `lesson_number` INT NOT NULL,
    `classroom` INT NOT NULL,
    `schoolclass_id` INT NOT NULL,
    `subject_id` INT NOT NULL,
    `teacher_id` INT NOT NULL,
    PRIMARY KEY (`id`),
    INDEX `schedule_ibfk_1` (`schoolclass_id` ASC) VISIBLE,
    INDEX `schedule_ibfk_2` (`subject_id` ASC) VISIBLE,
    INDEX `schedule_ibfk_3` (`teacher_id` ASC) VISIBLE,
    CONSTRAINT `schedule_ibfk_1`
    FOREIGN KEY (`schoolclass_id`)
    REFERENCES `demo`.`schoolclass` (`id`),
    CONSTRAINT `schedule_ibfk_2`
    FOREIGN KEY (`subject_id`)
    REFERENCES `demo`.`subject` (`id`),
    CONSTRAINT `schedule_ibfk_3`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `demo`.`teacher` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 15
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`lesson`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`lesson` (
                                               `id` INT NOT NULL AUTO_INCREMENT,
                                               `date` VARCHAR(45) NULL DEFAULT NULL,
    `topic` VARCHAR(255) NULL DEFAULT NULL,
    `homework` VARCHAR(255) NULL DEFAULT NULL,
    `schedule_id` INT NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    INDEX `FK_lesson_schedule_idx` (`schedule_id` ASC) VISIBLE,
    CONSTRAINT `FK_lesson_schedule`
    FOREIGN KEY (`schedule_id`)
    REFERENCES `demo`.`schedule` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 52
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`schoolchild`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`schoolchild` (
                                                    `id` INT NOT NULL AUTO_INCREMENT,
                                                    `name` VARCHAR(100) NOT NULL,
    `user_id` INT NULL DEFAULT NULL,
    `enabled` TINYINT(1) NOT NULL DEFAULT '1',
    PRIMARY KEY (`id`),
    UNIQUE INDEX `user_id` (`user_id` ASC) VISIBLE,
    CONSTRAINT `schoolchild_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `demo`.`user` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 12
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`grade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`grade` (
                                              `id` INT NOT NULL AUTO_INCREMENT,
                                              `value` INT NOT NULL,
                                              `lesson_id` INT NULL DEFAULT NULL,
                                              `schoolchild_id` INT NULL DEFAULT NULL,
                                              PRIMARY KEY (`id`),
    INDEX `lesson_id` (`lesson_id` ASC) VISIBLE,
    INDEX `schoolchild_id` (`schoolchild_id` ASC) VISIBLE,
    CONSTRAINT `grade_ibfk_1`
    FOREIGN KEY (`lesson_id`)
    REFERENCES `demo`.`lesson` (`id`),
    CONSTRAINT `grade_ibfk_2`
    FOREIGN KEY (`schoolchild_id`)
    REFERENCES `demo`.`schoolchild` (`id`))
    ENGINE = InnoDB
    AUTO_INCREMENT = 8
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`schoolchild_schoolclass`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`schoolchild_schoolclass` (
                                                                `schoolchild_id` INT NOT NULL,
                                                                `schoolclass_id` INT NOT NULL,
                                                                PRIMARY KEY (`schoolchild_id`, `schoolclass_id`),
    INDEX `schoolclass_id` (`schoolclass_id` ASC) VISIBLE,
    CONSTRAINT `schoolchild_schoolclass_ibfk_1`
    FOREIGN KEY (`schoolchild_id`)
    REFERENCES `demo`.`schoolchild` (`id`),
    CONSTRAINT `schoolchild_schoolclass_ibfk_2`
    FOREIGN KEY (`schoolclass_id`)
    REFERENCES `demo`.`schoolclass` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`teacher_subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`teacher_subject` (
                                                        `teacher_id` INT NOT NULL,
                                                        `subject_id` INT NOT NULL,
                                                        PRIMARY KEY (`teacher_id`, `subject_id`),
    INDEX `subject_id` (`subject_id` ASC) VISIBLE,
    CONSTRAINT `teacher_subject_ibfk_1`
    FOREIGN KEY (`teacher_id`)
    REFERENCES `demo`.`teacher` (`id`),
    CONSTRAINT `teacher_subject_ibfk_2`
    FOREIGN KEY (`subject_id`)
    REFERENCES `demo`.`subject` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `demo`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `demo`.`user_roles` (
                                                   `user_id` INT NOT NULL,
                                                   `roles` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`user_id`),
    CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `demo`.`user` (`id`))
    ENGINE = InnoDB
    DEFAULT CHARACTER SET = utf8mb4
    COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
